name: device-ui

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_PATH: project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_PATH }}
          submodules: recursive

      - name: check license headers
        env:
          CI_COMPONENTS_PATH: ${{ env.SOURCE_PATH }}/ci-components
          PROJECT_PATH: ${{ env.SOURCE_PATH }}
        shell: bash
        run: |
          ${{ ENV.SOURCE_PATH }}/ci-components/scripts/fmt/check_license.sh

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build web GUI
        shell: bash
        run: |
          cd ${{ env.SOURCE_PATH }}

          npm install
          npm run test
          npm run build
          npm run fmt

          if [ -n "$(git status --porcelain .)" ]; then
            echo "Please run 'npm run fmt' and commit the updated files."
            exit 1
          fi
